- .circleci/config.yml
> Feat: Update zapptool in order to support npm plugins install

- ZappApple/AppDelegateBase.swift
- ZappiOS/ZappiOS/AppDelegate.swift
> Feat: Add base implementation of Push notifications

- .gitignore
- ZappTvOS/Podfile
- ZappiOS/Podfile
> Feat: Update new version for Core frameworks 2020.2.4.19-2-2

- .circleci/config.yml
- ZappTvOS/package.json
- ZappiOS/package.json
> Feat: Update quck-brick-apple-2.2.1-rc.14

- ZappApple/AppDelegateBase.swift
- ZappTvOS/ZappTvOS.xcodeproj/project.pbxproj
- ZappiOS/Podfile
1. Remove AIS
2. Add For iOS podspec folder structure
3. Add Xcode script to resolve builds issue
> Feat: Remove AIS

- ZappTvOS/Podfile
- ZappiOS/Podfile
> Fix: Pointers issue with AIS

- ZappApple/AppDelegateBase.swift
- ZappTvOS/Podfile
- ZappTvOS/ZappTvOS/Base.lproj/Main.storyboard
- ZappiOS/Podfile
- ZappiOS/ZappiOS/AppDelegate.swift
- ZappiOS/ZappiOS/Base.lproj/Main.storyboard
Was before: RootViewController was as Root of the window. This VC had two containers. Spash and UILayerPlugin, that was added regarding needs.
Now: RootViewController migrated to RootController. SplashVC and UILayerPluginVC added as Root of the window regarding the needs
[Ticket](https://applicaster.atlassian.net/browse/ZPP-1372?atlOrigin=eyJpIjoiMzQ1MTdlMDIzZjZmNDQzNGJlMTc4OWY3NjM0YjBjMDYiLCJwIjoiaiJ9)
[Relevant PR](https://github.com/applicaster/AppleApplicasterFrameworks/pull/23)
> …
> Feat: Refactor of structure from RootViewController to RootController

- ZappTvOS/Podfile
- ZappTvOS/Podfile.lock
- ZappTvOS/ZappTvOS.xcodeproj/project.pbxproj
- ZappiOS/Podfile
- ZappiOS/Podfile.lock
- ZappiOS/ZappiOS.xcodeproj/project.pbxproj
1. Make iOS SDK minimum 11
[Ticket](https://applicaster.atlassian.net/browse/ZPP-1434)
2. Make tvOS SDK minimum 11
[Ticket](https://applicaster.atlassian.net/browse/ZPP-1435)
> Feat: Set minimum ios and tvos 11

- ZappTvOS/package.json
- ZappTvOS/yarn.lock
- ZappiOS/package.json
- ZappiOS/yarn.lock
This PR updates the version of QB native package to include changes related to handling of orientation in QB
> chore: bump version of quick brick native package

- .circleci/config.yml
- Scripts/assets-generator.sh
- ZappTvOS/Podfile
- ZappiOS/Podfile
- ZappiOS/ZappiOS.xcodeproj/project.pbxproj
- ZappiOS/ZappiOS/Base.lproj/Main.storyboard
set clear color for splash image container and video player
add new splash images
- updated on 20.0.0-Dev - https://zapp.applicaster.com/admin/sdk_versions/716de101-fd6f-404b-a5fd-5f44fd506cd0/asset_keys
> chore(splash) - set clear color for splash image container and video player + add new images

- ZappTvOS/package.json
- ZappTvOS/yarn.lock
- ZappiOS/package.json
- ZappiOS/yarn.lock
This PR updates the reference to quick-brick-native-apple repo to account for the changes done to tvos (missing orientation methods)
> chore: update quick-brick-native-apple to 2.2.1-rc.24

- .github/CODEOWNERS
> Feat: Add codeowners

- .circleci/config.yml
> Feat: Add zapptool version to 3.9.2

- ZappApple/AppDelegateBase.swift
- ZappiOS/Podfile
Adding support for universal links from user activity hooks
> chore(UL) - adding support for universal links from user activity hooks

- ZappApple/AppDelegateBase.swift
change uuid by url scheme call
https://applicaster.atlassian.net/browse/ZPP-1496
> feat(urlscheme) - change uuid by url scheme call

- Gemfile
- Gemfile.lock
- ZappApple/AppDelegateBase.swift
- ZappTvOS/Podfile
- ZappTvOS/Podfile.lock
- ZappiOS/Podfile
- ZappiOS/Podfile.lock
Add support of the legacy plugin analytics SDK
> Feat: Add analytics legacy support

- ZappTvOS/package.json
- ZappiOS/package.json
> Feat: Add solution to fix xcode console because RN bug

- .circleci/config.yml
With typo in .circle.yaml to prepare dev project app
> Bug: fix dev project path

- .circleci/config.yml
> Feat: Bump ZappTool Version 3.9.3 that supports skipping RN dependncies as pods

- dev_project_whitelist_ios.txt
- dev_project_whitelist_tvos.txt
> Fix: Dev projects whitellist files

- ZappApple/AppDelegateBase.swift
- ZappApple/Helpers/FirebaseHandler/FirebaseHandler.swift
- ZappTvOS/Podfile
- ZappTvOS/ZappTvOS.xcodeproj/project.pbxproj
- ZappiOS/Podfile
- ZappiOS/ZappiOS.xcodeproj/project.pbxproj
> Feat: Add firebase hellper

- ZappiOS/ZappiOS/AppDelegate.swift
In order to make AppCenter crash log to call exactly after launch
> Feat: Add MsAppCenterHandler

- ZappApple/AppDelegateBase.swift
- ZappTvOS/Podfile
- ZappiOS/Podfile
[Ticket](https://applicaster.atlassian.net/browse/ZPP-1731?atlOrigin=eyJpIjoiZmUzZWYzMzhjYmM5NGMxMWFjMmYzMjg5ZDM1NDg1MDkiLCJwIjoiaiJ9)
[ZappApple](https://github.com/applicaster/AppleApplicasterFrameworks/pull/47)
> Feat: Add Audience for ios and tvos

- CHANGELOG.md
- ZappTvOS/package.json
- ZappiOS/package.json
Add Quickbrick version `2.3.0`. Prepare SDK for release
> Prepare release SDK 20.0.0 [from_716de101-fd6f-404b-a5fd-5f44fd506cd0]

- CHANGELOG.md
Share change log within iOS and tvOS versions
> Chore: Share change log tvOS and iOS

- ZappiOS/NotificationServiceExtension/NotificationService+Helper.swift
- ZappiOS/NotificationServiceExtension/NotificationService.swift
- ZappiOS/Podfile
- ZappiOS/ZappiOS.xcodeproj/project.pbxproj
refactor and activation of notification service extension
> Rich push notification support

- ZappApple/AppDelegateBase.swift
This data required to generate cell style url 
> Feat: Add family id to session strage

- .circleci/config.yml
> Feat: Set zapptool version 3.9.6

- ZappTvOS/Podfile
- ZappiOS/Podfile
> Chore: Improve Local notification manger

- ZappiOS/Podfile
> chore(zapp-apple) - Update version of zapp apple

- ZappTvOS/Podfile
- ZappiOS/Podfile
> ZappApple update for tvos

- fastlane/FastfileEnterprise
remove custom entitlements for enterprise builds
> chore(ent build) - remove custom entitlements for enterprise builds

- Gemfile
- ZappTvOS/Podfile.lock
- ZappTvOS/ZappTvOS.xcodeproj/project.pbxproj
- ZappTvOS/package.json
- ZappiOS/Podfile.lock
- ZappiOS/package.json
> Chore: Prepare for code freeze

- .circleci/config.yml
- Gemfile.lock
- ZappTvOS/package.json
- ZappiOS/package.json
1. Set CocoaPods: 1.9.1
2. Change circle image to support Xcode 11.4.0
3. Set in circle node version 12.0.0
https://discuss.circleci.com/t/change-node-version-in-macos-executor/34327/2
> Feat: Set xCode 11.4.0

- .circleci/config.yml
- ZappApple/AppDelegateBase.swift
- ZappTvOS/Podfile
- ZappiOS/Podfile
> Feat: Add store key to 

- ZappApple/AppDelegateBase.swift
- fastlane/EnvironmentHelper.rb
- fastlane/FastfileBase
- fastlane/FastfileEnterprise
- fastlane/FastfileStore
Adding changes to support the s3 hostname
https://applicaster.atlassian.net/browse/ZPP-2089
> chore(s3) - adding changes to support the s3 hostname

- ZappiOS/Podfile
Update version of ZappPlugins and ZappCore
> Update version of ZappPlugins and ZappCore

- ZappTvOS/package.json
- ZappiOS/package.json
> chore(QB) - Update QB version to 3.0.1

- ZappTvOS/Podfile
- ZappiOS/Podfile
> Bug-Zpp-2412: Fix path for ios splash video

- ZappTvOS/Podfile
Update ZappCore version on ZappTvOS
> chore() - Update ZappCore version on ZappTvOS

- ZappApple/AppDelegateBase.swift
- ZappTvOS/Podfile
- ZappiOS/Podfile
> chore(params) - adding device params

- ZappiOS/package.json
> Add dev quickbrick cli 3.1.0-rc.ca914400

- fastlane/Base/AppExtensions.rb
- fastlane/Base/BuildType.rb
- fastlane/Base/Helpers/AppCenterHelper.rb
- fastlane/Base/Helpers/BaseHelper.rb
- fastlane/Base/Helpers/EnvironmentHelper.rb
- fastlane/Base/Helpers/FirebaseHelper.rb
- fastlane/Base/Helpers/ProjectHelper.rb
- fastlane/BuildTypeFactory.rb
- fastlane/Enterprise/BuildTypeEnterprise.rb
- fastlane/Enterprise/Types/Client/Client.rb
- fastlane/Enterprise/Types/Debug/AppExtensions.rb
- fastlane/Enterprise/Types/Debug/Debug.rb
- fastlane/FaslaneUpload.rb
- fastlane/Fastfile
- fastlane/Store/Store.rb
> adding indentation, temp pr

- ZappiOS/Podfile
Update ZappPlugins to new version without UIWebView
> chore(UIWebView) - Update ZappPlugins to new version without UIWebView

- .circleci/config.yml
Add circle CI filters to support workflows for tags
> Chore: Add circle CI filters

- ZappiOS/package.json
- ZappiOS/yarn.lock
Update package.json required for latest QB
> Chore: resolve package issue for RN 0.60.2

- Scripts/react-native-patch.js
[ZPP-2465](https://applicaster.atlassian.net/browse/ZPP-2465)
in a new version of the RN 0.62-2 - remote menu button is used only to exit the app, I am adding a line of code that was exiting in previous versions of RN and sending as event 'menu' when the menu button is pressed.
the event "menu" we are using to exiting from the player, to navigate properly through connected screens or screen picker. ( navigate go back or exit the app when we are at the home screen)
> patch(tvOS): enabling remote menu button

- ZappTvOS/Podfile
- ZappiOS/Podfile
> Feat: Add support new key for sessions storage advertisingIdentifier

- fastlane/Base/Helpers/AppCenterHelper.rb
Add correct appname to appcenter post
> chore(appcenter) - add correct appname to appcenter post

- ZappTvOS/Podfile
- ZappiOS/Podfile
Update dependencies to new versions
> chore() - Update dependencies to new versions

- ZappiOS/Podfile
> fix for podfile

- .circleci/config.yml
Update for cache and Xcode version
> chore(xc) - Update for cache and Xcode version

- .circleci/config.yml
- fastlane/Fastfile
> chore(s3) - move to from fastlane to circle step

- .circleci/config.yml
- ZappTvOS/package.json
- ZappiOS/package.json
This PR adds the option to build a non minified RN bundle
> feat: add script to build non minified RN bundle

- ZappTvOS/package.json
- ZappTvOS/yarn.lock
This PR adds resolutions to the package.json files.
This allow to fix vulnerabilities by forcing yarn to resolve a certain version of a package, regardless of what is required by the dependencies
> chore: add resolutions to package.json files

- ZappApple/AppDelegateBase.swift
> Fix: session storage has no plugins

- .circleci/config.yml
Started the build process for iOS SDK 0.2.0-Dev which pulls from master, and ran into another [failure](https://app.circleci.com/pipelines/github/applicaster/ZappAppleBuilder/3873/workflows/0dc10ed7-d501-473a-aa46-672bf9a4fac6/jobs/4332).
```
/bin/bash: line 22: ../ZappTool/ZappTool : No such file or directory
```
I missed this because I didn't try running the last fix in circleci. 
Learned my lesson, after running in SSH I see that we don't need the space in:
```
"../ZappTool/ZappTool ${ZAPPTOOL_FLAGS}"
```
So after making that change I get:
- I believe that nobody is going to be able to build without this
- There [is another build issue ](https://app.circleci.com/pipelines/github/applicaster/ZappAppleBuilder/3874/workflows/684c862c-9a23-4400-aa63-aa17bf96dbdc/jobs/4324) affecting the RC …
> fix: circleci build script

- ZappTvOS/Podfile.lock
- ZappTvOS/package.json
- ZappTvOS/yarn.lock
- ZappiOS/Podfile.lock
- ZappiOS/ZappiOS/AppDelegate.swift
- ZappiOS/package.json
- ZappiOS/yarn.lock
> Feat: Add support of 3d actions handlers

- .circleci/config.yml
Enable large container feature. To use more powerful device for CI builds
[Circle CI DOCS](https://circleci.com/docs/2.0/configuration-reference/#resource_class)
> Feat: Enable Large Resources in CircleCi

- ZappApple/AppDelegateBase.swift
- ZappApple/Helpers/FirebaseHandler/FirebaseHandler.swift
- ZappTvOS/package.json
- ZappTvOS/yarn.lock
- ZappiOS/ZappiOS/AppDelegate.swift
- ZappiOS/package.json
- ZappiOS/yarn.lock
> Add logs to AppDelegate [WIP]

- ZappTvOS/package.json
- ZappTvOS/yarn.lock
- ZappiOS/package.json
- ZappiOS/yarn.lock
> Chore: Set ZappApple version 0.8.16

- ZappiOS/package.json
- ZappiOS/yarn.lock
> Bug: remove logger plugin from default packages

- .circleci/config.yml
react_native_packager_root - Add local server as example `localhost:8081`
skip_bundle_minification - Allow build not minificatied js bundle
> Bug: Fix Circle with QB bundle creation keys

- .circleci/config.yml
This PR updates the version of zapptool 
> chore: update zapptool version

- ZappiOS/ZappiOS/Info.plist
Remove audio from background modes
> chore(bg modes) - Remove audio from background modes

- Scripts/react-native-patch.js
We need add a react-native patch available also for tvOS, in order to fix the microphone dictation with react-native
https://applicaster.atlassian.net/browse/IM-844
Currently, react-native have a bug when words are dictated from microphone, cutting the voice. This is a custom react-native changes based on discussion on that ticket: https://applicaster.atlassian.net/browse/IM-117
- steps to reproduce a bug : described here : https://applicaster.atlassian.net/browse/IM-117
- expected result: Microphone works on user dictaction.
> Fix: IM-844, patch react-native tvOS

- ZappTvOS/package.json
- ZappTvOS/yarn.lock
- ZappiOS/package.json
- ZappiOS/yarn.lock
> Remove idfa

- ZappTvOS/package.json
- ZappTvOS/yarn.lock
- ZappiOS/package.json
- ZappiOS/yarn.lock
update versions:
"@applicaster/zapp-apple": “0.9.3”,
"@applicaster/zapp-core": "0.13.5”,
> add PlayerAdObserverProtocol

- ZappApple/Helpers/FirebaseHandler/FirebaseHandler.swift
> Resolve const logs issues

- ZappTvOS/package.json
- ZappTvOS/yarn.lock
- ZappiOS/package.json
- ZappiOS/yarn.lock
> Remove support AppCenter analytics from default SDK

- fastlane/Base/AppExtensions.rb
- fastlane/Base/BuildType.rb
- fastlane/Base/Helpers/BaseHelper.rb
- fastlane/Enterprise/BuildTypeEnterprise.rb
- fastlane/Enterprise/Types/Client/Client.rb
- fastlane/Enterprise/Types/Debug/AppExtensions.rb
- fastlane/Enterprise/Types/Debug/Debug.rb
- fastlane/Store/Store.rb
> chore(1.0.0) - Merge changes from 1.0.0-RC

- ZappiOS/ZappiOS/Info.plist
Adding key for idfa usage description
> chore(idfa) - Adding key for idfa usage description

- fastlane/Base/AppExtensions.rb
- fastlane/Base/Helpers/BaseHelper.rb
- fastlane/Enterprise/Types/Client/Client.rb
- fastlane/Enterprise/Types/Debug/AppExtensions.rb
- fastlane/Enterprise/Types/Debug/Debug.rb
- fastlane/Store/Store.rb
> fix(fastlane) - fix for build params

- ZappTvOS/package.json
- ZappiOS/package.json
> chore(qb) - Update QB to 4.1.0

- ZappApple/AppDelegateBase.swift
- ZappApple/Customization/FeaturesCustomization.plist
- ZappTvOS/Podfile
- ZappTvOS/ZappTvOS/Info.plist
- ZappTvOS/package.json
- ZappTvOS/yarn.lock
- ZappiOS/Podfile
- ZappiOS/package.json
- ZappiOS/yarn.lock
- fastlane/Base/BuildType.rb
> Add support of debug env

- ZappTvOS/package.json
- ZappTvOS/yarn.lock
- ZappiOS/package.json
- ZappiOS/yarn.lock
> Bump xray logger version to 0.0.8-alpha

- fastlane/Base/BuildType.rb
- fastlane/BuildTypeFactory.rb
- fastlane/Enterprise/Types/Client/Client.rb
- fastlane/Enterprise/Types/Debug/Debug.rb
- fastlane/Store/Store.rb
Build release build for enterprise
> feat(enterprise) - Build release build for enterprise

- ZappiOS/ZappiOS/Info.plist
Add support for AirPlay2
https://developer.apple.com/documentation/avfoundation/media_playback_and_selection/airplay_2/getting_airplay_2_into_your_app
> feat(AirPlay2) - Add support for AirPlay2

- rake/tasks/fetch_ms_app_center_app_data.rake
update to remove additional calls and put logs
> chore(app center) - update to remove additional calls and put logs

- ZappTvOS/package.json
- ZappTvOS/yarn.lock
- ZappiOS/package.json
- ZappiOS/yarn.lock
> Resolve xray issues

- .circleci/config.yml
- ZappTvOS/ZappTvOS.xcodeproj/project.pbxproj
- ZappiOS/ZappiOS.xcodeproj/project.pbxproj
Update deployment target to 11.0
> chore(target version) - Update deployment target to 11.0

- ZappTvOS/package.json
- ZappTvOS/yarn.lock
- ZappiOS/package.json
- ZappiOS/yarn.lock
> Set xray version 0.0.12-alpha

- ZappTvOS/package.json
- ZappTvOS/yarn.lock
- ZappiOS/package.json
- ZappiOS/yarn.lock
> Set xray version 0.13

- ZappTvOS/package.json
- ZappiOS/package.json
chore(ver) - Update versions of dependencies
> chore(ver) - Update versions of dependencies

- ZappTvOS/package.json
- ZappiOS/ZappiOS/AppDelegate+UNUserNotificationCenterDelegate.swift
- ZappiOS/package.json
Update versions of dependencies
> chore(links) - Open web url with internal safari if not stated to be external

- ZappTvOS/package.json
- ZappiOS/ZappiOS/AppDelegate.swift
- ZappiOS/package.json
> fix(logger) - save data as string

- .github/PULL_REQUEST_TEMPLATE.md
Fix Pull request template according latest needs
> Refactor PULL_REQUEST_TEMPLATE.md

- README.md
Update Readme.md of the repo with latest data
> Update readme file README.md

- .gitignore
Move to git ignore un relevant files
> fix: add to git ignore not relevant items

- .circleci/config.yml
> chore: Change Zapptool path to S3

- ZappTvOS/package.json
- ZappiOS/package.json
> chore: update xray to 0.0.15

- ZappiOS/package.json
- ZappiOS/yarn.lock
[Jira Ticket](https://applicaster.atlassian.net/browse/TPS-698)
This PR updates the version of the QuickBrick native apple pod
> chore: bump quick brick native apple version

- ZappTvOS/package.json
- ZappTvOS/yarn.lock
- ZappiOS/package.json
- ZappiOS/yarn.lock
> feat: add xray readable ui

- ZappTvOS/Podfile
- ZappiOS/Podfile
example of failed build
https://app.circleci.com/pipelines/github/applicaster/ZappAppleBuilder/5743/workflows/5760304f-dd93-4849-82f2-68c3a1d6dc6e/jobs/6665
issue:
https://github.com/CocoaPods/CocoaPods/issues/9902
> fix(headers) - Xcode 12 settings fail to build CocoaPods-generate umbrella headers

- ZappiOS/ZappiOS.xcodeproj/project.pbxproj
> chore: remove flipper key

- Scripts/react-native-patch.js
> chore: add script for blur component

- Scripts/react-native-patch.js
- fastlane/Base/Helpers/BaseHelper.rb
> merge master

- CHANGELOG.md
update changelog for sdk 1.0.0
> update changelog for sdk 1.0.0

- ZappTvOS/package.json
- ZappTvOS/yarn.lock
- ZappiOS/package.json
- ZappiOS/yarn.lock
> chore: migrate zapp-apple to 11.1

- ZappTvOS/package.json
- ZappiOS/package.json
fix: update xray version with fix in search subsystem and bg color
> fix: update xray version with fix in search subsystem and bg color

- ZappTvOS/package.json
- ZappiOS/package.json
update xray version, fix for bg color
> fix: update xray version, fix for bg color

- ZappTvOS/Podfile.lock
- ZappTvOS/yarn.lock
- ZappiOS/Podfile.lock
- ZappiOS/ZappiOS.xcodeproj/project.pbxproj
- ZappiOS/yarn.lock
This PR updates the lock files (yarn & pod) in the repo after dependency changes
> chore: update lock files

- ZappTvOS/package.json
- ZappiOS/package.json
set temporary version of xray to fix json file sink
> fix: set version of xray to fix json file sink

- ZappTvOS/package.json
- ZappTvOS/yarn.lock
- ZappiOS/package.json
- ZappiOS/yarn.lock
This PR updates the version of the QB native pod
> chore: update Qb native pod version

- ZappiOS/Podfile
- ZappiOS/Podfile.lock
- ZappiOS/package.json
- ZappiOS/yarn.lock
set new dependency for push and analytics plugins sdk
> feat: set new dependency for push and analytics plugins sdk

- ZappTvOS/package.json
- ZappTvOS/yarn.lock
- ZappiOS/package.json
- ZappiOS/yarn.lock
> fix: make audience not flow blocker

- ZappTvOS/ZappTvOS/Info.plist
- ZappiOS/ZappiOS/Info.plist
Remove NSUserTrackingUsageDescription key from the app
> chore: Remove NSUserTrackingUsageDescription key from the app

- CHANGELOG.md
- ZappTvOS/package.json
- ZappTvOS/yarn.lock
- ZappiOS/Podfile
- ZappiOS/package.json
- ZappiOS/yarn.lock
> chore: Prepare 2.0.0 for release

- ZappApple/AppDelegateBase.swift
> chore: add audio category logs

- ZappApple/AppDelegateBase.swift
> fix: remove unneeded setActive audio, it prevent to cal PIP and play now

- ZappTvOS/package.json
- ZappTvOS/yarn.lock
- ZappiOS/package.json
- ZappiOS/yarn.lock
> chore: add support check ip-adress with port

- ZappTvOS/Podfile
- ZappTvOS/package.json
- ZappiOS/NotificationServiceExtension/NotificationService.swift
- ZappiOS/Podfile
Adding support for analytics plugins in tvOS
also - removing custom settings from the notification service extension as supposed to be generic
> feat: Adding support for analytics plugins in tvOS

- ZappTvOS/package.json
- ZappTvOS/yarn.lock
- ZappiOS/package.json
- ZappiOS/yarn.lock
Add option to remove keys in session storage and local storage
> feat: add remove keys from storage

- Gemfile
- rake/tasks/fetch_ms_app_center_app_data.rake
Hi Guys,
I had a build failing due to some AppCenter issue.
Looking at the code it seems the code was using the `curl` command by running a shell command.
The exception in my build shows that the check for the status code was not functioning.
See exception in failing build: https://app.circleci.com/pipelines/github/applicaster/ZappAppleBuilder/6994/workflows/6ee4b478-0dd1-4a2e-b959-e7996f6d5d95/jobs/8175/parallel-runs/0/steps/0-126
- _if your PR is based on another branch …
> fix code using cURL via ruby in fetch_ms_app_center_app_data.rake

- .circleci/config.yml
add artifacts collection from build content
example build: https://app.circleci.com/pipelines/github/applicaster/ZappAppleBuilder/7056/workflows/c4f66e14-7d10-41f2-8182-35f066bb6f3f/jobs/8296
> chore: add artifacts collection from build content

- ZappTvOS/Podfile
- ZappiOS/Podfile
- ZappiOS/ZappiOS/AppDelegate.swift
1. suppress warning: "Your project does not explicitly specify the CocoaPods master specs repo"
2. call updates due to settings changes
3. remove deployment target on pods
> check one of the following type and make sure all …
> chore: maintenance for dependencies and settings

- ZappTvOS/package.json
- ZappTvOS/yarn.lock
- ZappiOS/package.json
- ZappiOS/yarn.lock
> chore: set xray verison 0.1.3

- ZappTvOS/package.json
- ZappTvOS/yarn.lock
- ZappiOS/package.json
- ZappiOS/yarn.lock
> chore: bump xray 0.1.4

- ZappTvOS/package.json
- ZappTvOS/yarn.lock
- ZappiOS/package.json
- ZappiOS/yarn.lock
> feat: add support keychain to local storage

- ZappTvOS/ZappTvOS/Entitlements/ZappTvOS-Debug.entitlements
- ZappTvOS/ZappTvOS/Entitlements/ZappTvOS-Release.entitlements
> chore: remove tvOS empty entitlments 

- fastlane/Base/Helpers/BaseHelper.rb
fix for adding app entitlements
> fix for adding app entitlements

- ZappApple/AppDelegateBase.swift
- ZappTvOS/package.json
- ZappTvOS/yarn.lock
- ZappiOS/package.json
- ZappiOS/yarn.lock
> Add support extandable app delegate

- CHANGELOG.md
Update changelog to prepare to 3.0.0 release
> chore: Update changelog to prepare to 3.0.0 release

- ZappTvOS/package.json
- ZappiOS/package.json
Update version of ZappApple to 1.3.0
> chore: Update version of ZappApple to 1.3.0

- Gemfile
- fastlane/Base/BuildType.rb
- fastlane/Base/Helpers/BaseHelper.rb
- fastlane/Base/Helpers/EnvironmentHelper.rb
- fastlane/Base/Helpers/ProjectHelper.rb
- fastlane/BuildTypeFactory.rb
- fastlane/Pluginfile
- fastlane/Store/Store.rb
Support AppStore API Key for store uploads
> feat: Support AppStore API Key for store uploads

- rake/templates/s3_ipa.html.erb
> fix: Update text on template

- ZappTvOS/package.json
- ZappiOS/package.json
> chore: Update dependencies versions

- .circleci/config.yml
- Gemfile
adding temp solution from fastlane PR 18116
> fix: set temp solution for 2FA

- .circleci/config.yml
- CHANGELOG.md
- Gemfile.lock
- fastlane/Base/BuildType.rb
Update to print store validation error
> chore: Update to print store validation error

- .circleci/config.yml
- CHANGELOG.md
Update Xcode version to 12.4.0
> chore: Update Xcode version to 12.4.0

- ZappTvOS/package.json
- ZappiOS/package.json
> chore: Update ZappApple version

- .circleci/config.yml
> fix: Add new WWDR Certificate

- ZappiOS/Podfile
- fastlane/Base/AppExtensions.rb
- fastlane/Base/BuildType.rb
- fastlane/Base/Helpers/ProjectHelper.rb
- fastlane/Fastfile
Removal of App Extensions and Flipper on local build
set `should_remove_app_extensions_on_local_build` parameter as **false** on podfile to keep app extensions on pod update
set `should_add_flipper_on_local_build` parameter as **true** on podfile to enable flipper 
> chore: Removal of App Extensions and Flipper on local build

- ZappTvOS/package.json
- ZappTvOS/yarn.lock
- ZappiOS/package.json
- ZappiOS/yarn.lock
Add support of the player plugin in ZappApple framework
> Add player plugin logic

- Scripts/podfile-helpers.rb
- ZappiOS/Podfile
Update podfile changes to remove extensions on preinstall
> fix: Update podfile changes to remove extensions on preinstall

- ZappTvOS/package.json
- ZappiOS/package.json
Update Xray version, fix for email handling
> chore: Update Xray version

- ZappApple/Helpers/FirebaseHandler/FirebaseHandler.swift
- ZappiOS/NotificationContentExtension/NotificationViewController.swift
- ZappiOS/NotificationServiceExtension/NotificationService.swift
- ZappiOS/ZappiOS/AppDelegate+UNUserNotificationCenterDelegate.swift
- ZappiOS/ZappiOS/AppDelegate.swift
- ZappiOS/ZappiOSTests/ZappiOSTests.swift
- ZappiOS/ZappiOSUITests/ZappiOSUITests.swift
> chore: indentations updates

- ZappTvOS/package.json
- ZappTvOS/yarn.lock
This PR updates the native QB pod to include a fix for initial focus
> feat: update tvos native pod

- ZappiOS/ZappiOS/Info.plist
> chore: remove backgroun audio key

- ZappTvOS/package.json
- ZappiOS/package.json
Update dependencies for Xray changes
> chore: Update dependencies for Xray changes

- Gemfile.lock
- fastlane/Base/BuildType.rb
- fastlane/Pluginfile
- fastlane/Store/Store.rb
Add store current version validation
> App version `1.1.2` for platform `tvos` is available in AppStoreConnect with `PENDING DEVELOPER RELEASE` state. Can not create a new version unless this version is released or rejected
> feat: Add store current version validation

- ZappiOS/Podfile
> fix: resolve issue where zapptool can not find a path to push extensions

- fastlane/Base/BuildType.rb
Validates that new version number is great than latest released app version 
**Error example:**
`ERROR ITMS-90062:This bundle is invalid. The value for key CFBundleShortVersionString [0.0.116] in the Info.plist file must contain a higher version than that of the previously approved version [1.1.1]. `
> feat: Add version validations

- Gemfile
- Gemfile.lock
- fastlane/Base/BuildType.rb
- fastlane/Store/Store.rb
Re-add api key right before the submission to store
Fastlane version bump
> chore: Update api key settings + fastlane version bump

- .circleci/config.yml
Update zapptool to support SKAdNetworks settings
> chore: Update zapptool to support SKAdNetworks settings

- ZappTvOS/Podfile.lock
- ZappTvOS/yarn.lock
- ZappiOS/Podfile.lock
- ZappiOS/package.json
- ZappiOS/yarn.lock
This PR adds webview module resolution required for the js2native interface
> chore: add webview resolutions

- .circleci/config.yml
- ZappiOS/set_up_repo.js
> feat: add script to set up repo

- fastlane/Base/BuildType.rb
- fastlane/Store/Store.rb
@alexzchut Is it enough or should we remove something else?
> Ignore upload to appcenter for debug builds

- .circleci/config.yml
> feat(circle-ci): add p7 ssh keys for gitlab private repos

- ZappiOS/package.json
- ZappiOS/yarn.lock
This PR adds the semver dependency to zapp ios package.json, which is required for the script introduced in #240 
> chore: add semver dev dependency to zappios

- ZappTvOS/Podfile
- ZappTvOS/Podfile.lock
- ZappTvOS/package.json
- ZappTvOS/yarn.lock
- ZappiOS/package.json
- ZappiOS/yarn.lock
This PR adds the safe area context library which is useful to get insets related to the safe areas in react native apps
https://github.com/th3rdwave/react-native-safe-area-context
> Add safe area lib

- ZappTvOS/package.json
- ZappTvOS/yarn.lock
- ZappiOS/package.json
- ZappiOS/yarn.lock
> chore: do not add tag in pushes if user disable push notification

- ZappiOS/ZappiOS/Info.plist
> chore: add audio background back

- ZappiOS/ZappiOS/AppDelegate+SilentRemoteNotificationHandler.swift
Updates to allow handling silent pushes having url schemes 
We will be able to use this same way as we are handling settings changes or generateNewUUID for example
> check one of the following type and make sure all related …
> feat: handle silent notification with url scheme and forward for handling by UrlSchemeHandler

- ZappTvOS/package.json
- ZappTvOS/yarn.lock
- ZappiOS/package.json
- ZappiOS/yarn.lock
Update for Network Request logging
> chore: Update for Network Request logging

- .circleci/config.yml
> chore: Remove not needed WWDR certificate

- ZappTvOS/Podfile
It fixes the crash caused by not-linked netinfo library
> feat(TvOs): linked netinfo podspec

- .circleci/config.yml
adding WWDR certificate to circle build
> fix: adding WWDR certificate to circle build

- ZappiOS/ZappiOS/AppDelegate+SilentRemoteNotificationHandler.swift
Add support for local push replace
> feat: Add support for local push replace

- Gemfile
- Gemfile.lock
Update fastlane version to 2.185.0
**_Unable to update to 2.185.1 due to [following](https://github.com/fastlane/fastlane/issues/18936) issue_**
> chore: Update fastlane version to 2.185.0

- ZappTvOS/package.json
- ZappTvOS/yarn.lock
- ZappiOS/package.json
- ZappiOS/yarn.lock
Update dependencies for push error handling
> chore: Update dependencies for push error handling

- .circleci/config.yml
- ZappTvOS/package.json
- ZappiOS/package.json
> chore: Update ZappApple to 2.5.1

- .circleci/config.yml
Change AWSClIv 2 according changes was made Jul15
https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-python-2-7-in-aws-sdk-for-python-and-aws-cli-v1
> Check new awccli

- .circleci/config.yml
Update Xcode version to 12.5.1
> chore: Update Xcode version to 12.5.1
