applicaster/ZappAppleBuilder

fastlane/FastfileEnterprise
fastlane/FastfileStore

Adding usage of legacy build because of symlink issue when archiving
https://circleci.com/gh/applicaster/ZappAppleBuilder/65

fix(archive) - adding usage of legacy build because of symlink issue when archiving

---

ZappTvOS/GoogleService-Info.plist
ZappTvOS/ZappTvOS.xcodeproj/project.pbxproj
ZappiOS/GoogleService-Info.plist
ZappiOS/ZappiOS.xcodeproj/project.pbxproj

Add google services plist dummy to allow to use base firebase plugin

Feat: Add google services plist

---

fastlane/FastfileEnterprise

Wrong application bundle cause upload all applications to same place enterprise apps and release

Bug: Fix wrong bundle indentifier for enterprice app

---

fastlane/FaslaneUpload.rb

Fix that broke tvOS builds during refactor iOS 
[Problematic PR](https://github.com/applicaster/ZappAppleBuilder/pull/32)

Bug: fix refactor of ios fastlane buid that spoil tvos

---

ZappiOS/ZappiOS/Info.plist

In order to use ReactNative's StatusBar component, we need to change this value in our plist

feat: allow status bar to be controlled from JS

---

.circleci/config.yml

This PR updates the repo to use zappTool 3.9.8 in order to support the new QB platforms

chore: update CI to use zapptool 3.9.8

---

ZappiOS/package.json
ZappiOS/yarn.lock

This PR updates ZappiOS to use `@applicaster/quick-brick-native-apple` to `4.0.0-rc.2`

chore: update qb apple dependency

---

Gemfile
fastlane/Base/BuildType.rb
fastlane/Pluginfile
fastlane/Store/Store.rb

Update for fastlane version to 2.150.0
Fix for certificate vs provision validation

chore(fl) - Update for fastlane version to 2.150.0

---

Scripts/autolink-react-dependencies.rb
ZappiOS/Podfile
ZappiOS/package.json
ZappiOS/yarn.lock

Adding React-native native dependency for the ViewPager components.
It's required to use ViewPager component on QB apps. 

feat: add view pager react-native dependency

---

.circleci/config.yml

This PR reads the new zapp build flag to enable options for building the react-native bundle

add zapptool flags for new RN build options

---

ZappTvOS/package.json
ZappTvOS/yarn.lock
ZappiOS/package.json
ZappiOS/yarn.lock

Resolve issue where RNManager use session storage before it was initialized

Chore: bug zapp-apple to version 0.8.17

---

Scripts/autolink-react-dependencies.rb
ZappTvOS/package.json
ZappTvOS/yarn.lock
ZappiOS/package.json
ZappiOS/yarn.lock

Ticket:  https://applicaster.atlassian.net/browse/TPS-397
This PR is adding an svg and linear gradient to android TV and to auto-linking script. 
Aim of this task is to add dependencies use throughout QB app to the SDK so there is no need for the user to add a plugin in zapp.
This is a breaking change, we will need to release new RC.

feat: add qb native dependencies

---

ZappTvOS/package.json
ZappTvOS/yarn.lock
ZappiOS/package.json
ZappiOS/yarn.lock

This PR removes the explicit dependencies to the QB player, RN linear gradient package, and other (non core) plugin-related dependencies which are causing builds to fail when a different version is being used in Zapp

chore: remove unneeded dependencies

---

ZappTvOS/package.json
ZappTvOS/yarn.lock
ZappiOS/Podfile
ZappiOS/package.json
ZappiOS/yarn.lock

This PR adds react-native-webview as a core dependency, as webview component is now a core plugin and relies on this.
I also added back the linear gradient module as I wasn't aware when I removed it that it had been removed form the manifest of the QB player from 3.0.1-beta.6 onwards

chore: add core dependencies

---

Scripts/react-native-patch.js

[Fix of the issue](https://stackoverflow.com/questions/62612812/all-image-fast-image-in-react-native-app-not-working-on-ios-14-beta-and-xcode-12)
Issue resolved in RN: `0.63.2`

Patch RCimage in iOS 14, does not work in RN 0.62.2

---

Scripts/react-native-patch.js

This PR adds an option to our patch script to add React-Core dependency to podspec which are missing it.
This is currently applied to react-native-linear-gradient and react-native blur, only for tvOS.
I also added a flag to skip the patch on a file if the file doesn't exist, instead of failing the entire process like it used to.

feat: add patch to apply React-Core dependency in podspecs

---

ZappTvOS/package.json
ZappTvOS/yarn.lock
ZappiOS/package.json
ZappiOS/yarn.lock

This PR updates the version of the quick-brick-native-apple pod to the rc version 4.1.2-rc.2

chore: update quick-brick-native-apple pod

---

ZappTvOS/Podfile.lock
ZappTvOS/package.json
ZappTvOS/yarn.lock
ZappiOS/Podfile.lock
ZappiOS/ZappiOS.xcodeproj/project.pbxproj
ZappiOS/package.json
ZappiOS/yarn.lock

this PR updates the quick-brick-native apple pod to 4.1.2-rc.7

chore: update qb pod to 4.1.2-rc.7

---

.circleci/config.yml

Not rotate styles in zapptool in format `RGBAHex`
AppleBuilder is using format `ARGBHex`
[ZPP-2977](https://applicaster.atlassian.net/browse/ZPP-2977)

fix: remove rotaion styles from zapptool

---

ZappiOS/ZappiOS/Entitlements/ZappiOS-Debug.entitlements
ZappiOS/ZappiOS/Entitlements/ZappiOS-Release.entitlements

Apple does not allow any more to upload apps with empty entitlements 
Error example: https://app.circleci.com/pipelines/github/applicaster/ZappAppleBuilder/7279/workflows/f2096160-64bb-4ff7-bbb9-31b3f8defbe6/jobs/8596

chore: remove empty entitlements

---

fastlane/Base/BuildType.rb

limit app version validation to new app versions only and compare with store version

fix: limit app version validation to new app versions only

---

ZappTvOS/package.json
ZappTvOS/yarn.lock
ZappiOS/package.json
ZappiOS/yarn.lock

[Monday](https://applicaster.monday.com/boards/1139872912/pulses/1199317061)
This PR adds the react-native-gesture-handler library for apple platforms

feat: add react-native-gesture-handler library

---

ZappiOS/package.json
ZappiOS/yarn.lock

This PR updates the version of zapp-core to 1.6.1 
Builds were failing this morning on the dev SDK, and this fixes the issue
⚠️  the [4.1.0-Dev sdk](https://zapp.applicaster.com/admin/sdk_versions/0776bae4-b145-4fe6-9acc-f9c65ef139e3/edit) is pointing to that branch, so it should be updated after this is merged

chore: update zapp-core version

---

ZappTvOS/package.json
ZappTvOS/yarn.lock
ZappiOS/yarn.lock

This PR adds the netinfo module on tvos. this is required as it is used by quick-brick-core
it also adds resolution to the tvos package in case some dependency are trying to import react-native

chore: add netinfo on tvos
